include:
 - sketch:
    - extras/arduino-examples/examples/01.Basics/Blink/Blink.ino
    - extras/arduino-examples/examples/03.Analog/AnalogInOutSerial/AnalogInOutSerial.ino
    - extras/arduino-examples/examples/02.Digital/toneMultiple/toneMultiple.ino
    - extras/arduino-examples/examples/06.Sensors/Memsic2125/Memsic2125.ino
    - extras/arduino-examples/examples/08.Strings/StringConstructors/StringConstructors.ino
    - libraries/BLE/examples/BLEBeginEnd/BLEBeginEnd.ino
    - libraries/BLE/examples/CentralScan/CentralScan.ino
    - libraries/BLE/examples/CentralScanConnect/CentralScanConnect.ino
    - libraries/BLE/examples/CentralConnect/CentralConnect.ino
    - libraries/BLE/examples/PeripheralAdvertise/PeripheralAdvertise.ino
    - libraries/BLE/examples/PeripheralConnect/PeripheralConnect.ino
    - libraries/BLE/examples/PeripheralGATTServer/PeripheralGATTServer.ino

exclude:
   - fqbn: infineon:psoc6:cy8cproto_063_ble
     sketch:
      - libraries/WiFi/examples/ConnectNoEncryption/ConnectNoEncryption.ino
      - libraries/WiFi/examples/ConnectWithWPA/ConnectWithWPA.ino
      - libraries/WiFi/examples/ScanNetworks/ScanNetworks.ino
      - libraries/WiFi/examples/SimpleWebServerWiFi/SimpleWebServerWiFi.ino
      - libraries/WiFi/examples/WiFiPing/WiFiPing.ino
      - libraries/WiFi/examples/WiFiUdpNtpClient/WiFiUdpNtpClient.ino
      - libraries/WiFi/examples/WiFiUdpReceiver/WiFiUdpReceiver.ino
      - libraries/WiFi/examples/WiFiUdpSender/WiFiUdpSender.ino
      - libraries/WiFi/examples/WiFiWebClient/WiFiWebClient.ino
      - libraries/PDM/examples/raw_data_output/raw_data_output.ino

   - fqbn: infineon:psoc6:cy8ckit_062s2_ai
     sketch:
      - libraries/BLE/examples/BLEBeginEnd/BLEBeginEnd.ino
      - libraries/BLE/examples/CentralScan/CentralScan.ino
      - libraries/BLE/examples/CentralScanConnect/CentralScanConnect.ino
      - libraries/BLE/examples/CentralConnect/CentralConnect.ino
      - libraries/BLE/examples/PeripheralAdvertise/PeripheralAdvertise.ino
      - libraries/BLE/examples/PeripheralConnect/PeripheralConnect.ino
      - libraries/BLE/examples/PeripheralGATTServer/PeripheralGATTServer.ino
