name=BLE
version=0.1.0
author=Infineon Technologies AG
maintainer=Infineon Technologies AG <maker@infineon.com>
sentence=Enables Bluetooth Low Energy connectivity for PSOC6 BLE-capable core boards
paragraph=
category=Communication
url=https://github.com/Infineon/arduino-core-psoc6/tree/main/libraries/BLE
architectures=psoc6
includes=BLE.h
