options:
  USE_CORE:
    name: local
    url: "https://arduino-core-psoc6.readthedocs.io/en/latest/index.html"
  SEND_JOB_START_TOKEN: true

compile:
    compile-psoc6-cy8ckit_062s2_ai:
      description: Compiling test_digitalio_single.cpp for PSOC6 platform
      command: make -f Makefile.arduino.mk test_digitalio_single compile
      fqbns: [infineon:psoc6:cy8ckit_062s2_ai]
      working_dir: tests/arduino-core-tests

code-quality:
    source-code-quality-clang-tidy:
      description: clang-tidy check sources
      tool: clang-tidy
      command: extras/makers-devops/tools/code_checks/run_clang_tidy.sh ./cores/psoc6/* ./libraries/*

    source-code-quality-cppcheck:
      description: cppcheck check sources
      tool: cppcheck
      command: extras/makers-devops/tools/code_checks/run_cppcheck.sh ./cores/psoc6/* ./libraries/*  
               | -I extras/arduino-core-api/api/ -I variants/CY8CKIT-062S2-AI/mtb-bsp -I extras/mtb-libs/core-lib/include 
               | -I libraries/WiFi/src -I libraries/Wire/src -I libraries/SPI/src -I extras/mtb-libs/mtb-hal-cat1/include
               | -I extras/mtb-libs/wifi-connection-manager/include --suppress=*:extras/mtb-libs/wifi-connection-manager/include*
               | -I variants/CY8CKIT-062S2-AI -I cores/psoc6 --suppress=*:variants/CY8CKIT-062S2-AI/* --suppress=*:extras/mtb-libs/mtb-hal-cat1/include/*
               | --suppress=*:extras/arduino-core-api/api/* --suppress=*:cores/psoc6/api/* --suppress=*:variants/CY8CKIT-062S2-AI/mtb-bsp/* --suppress=*:extras/mtb-libs/core-lib/include/*
    
    test-code-quality-clang-tidy:
      description: clang-tidy check tests
      tool: clang-tidy
      command: extras/makers-devops/tools/code_checks/run_clang_tidy.sh ./tests/arduino-core-tests/src/*

    test-code-quality-cppcheck:
      description: cppcheck check tests
      tool: cppcheck
      command: extras/makers-devops/tools/code_checks/run_cppcheck.sh ./tests/arduino-core-tests/src/*  
               | -I extras/arduino-core-api/api/ -I variants/CY8CKIT-062S2-AI/mtb-bsp -I extras/mtb-libs/core-lib/include 
               | -I libraries/WiFi/src -I libraries/Wire/src -I libraries/SPI/src -I extras/mtb-libs/mtb-hal-cat1/include
               | -I extras/mtb-libs/wifi-connection-manager/include --suppress=*:extras/mtb-libs/wifi-connection-manager/include*
               | -I tests/arduino-core-tests/Unity/src --suppress=*:tests/arduino-core-tests/Unity/src/*
               | -I variants/CY8CKIT-062S2-AI -I cores/psoc6 --suppress=*:variants/CY8CKIT-062S2-AI/* --suppress=*:extras/mtb-libs/mtb-hal-cat1/include/*
               | --suppress=*:extras/arduino-core-api/api/* --suppress=*:cores/psoc6/api/* --suppress=*:variants/CY8CKIT-062S2-AI/mtb-bsp/* --suppress=*:extras/mtb-libs/core-lib/include/*

    code-quality-clang-format:
      description: clang-tidy check sources
      tool: clang-format
      command: extras/makers-devops/tools/code_checks/run_clang_format.sh ./cores/psoc6/* ./libraries/*

    code-quality-black-format:
      description: clang-tidy check sources
      tool: black-format
      command: extras/makers-devops/tools/code_checks/run_black.sh ./extras/makers-devops/tools/* 

unit-test:
    unit-test-digital-io:
      - description: Compiling, flashing and monitoring digital IO unit test.
        command: make test_digitalio_single 
        query: digital_io_single_board == '1:1'
        working_dir: extras/arduino-core-tests

    unit-test-tone:
      - description: Compiling, flashing and monitoring tone, no-tone unit test.
        command: make test_tone_no_tone 
        query: tone_no_tone_single_board == '1:1'
        working_dir: extras/arduino-core-tests

    unit-test-interrupts:
      - description: Compiling, flashing and monitoring Interrupts unit test.
        command: make test_interrupts_single 
        query: interrupts_single_board == '1:1'
        working_dir: extras/arduino-core-tests

    unit-test-random:
      - description: Compiling, flashing and monitoring random unit test.
        command: make test_random 
        query: random_single_board == '1:1'
        working_dir: extras/arduino-core-tests

    unit-test-time:
      - description: Compiling, flashing and monitoring Time unit test.
        command: make test_time_single 
        query: time_single_board == '1:1'
        working_dir: extras/arduino-core-tests
  
    unit-test-iic-pingpong:
      - description: Compiling, flashing and monitoring I2C pingpong slave unit test.
        command: make test_wire_connected2_slavepingpong 
        query: iic_ping_pong_multiple_boards_slave == '1:1'
        working_dir: extras/arduino-core-tests

      - description: Compiling, flashing and monitoring I2C pingpong master unit test.
        command: make test_wire_connected2_masterpingpong 
        query: iic_ping_pong_multiple_boards_master == '1:1'
        working_dir: extras/arduino-core-tests

    unit-test-spi-pingpong:
      - description: Compiling, flashing and monitoring SPI pingpong slave unit test.
        command: make test_spi_connected2_slavepingpong 
        query: spi_ping_pong_multiple_boards_slave == '1:1'
        working_dir: extras/arduino-core-tests

      - description: Compiling, flashing and monitoring SPI pingpong master unit test.
        command: make test_spi_connected2_masterpingpong 
        query: spi_ping_pong_multiple_boards_master == '1:1'
        working_dir: extras/arduino-core-tests

    unit-test-spi-loopback:
      - description: Compiling, flashing and monitoring SPI loopback unit test.
        command: make test_spi_connected1_loopback
        query: spi_ping_pong_single_board == '1:1'
        working_dir: extras/arduino-core-tests

    unit-test-iic-single-board:
      - description: Compiling, flashing and monitoring I2C single board unit test.
        command: make test_wire_connected1_pingpong
        query: iic_ping_pong_single_board == '1:1'
        working_dir: extras/arduino-core-tests

    unit-test-analog-io-adc:
      - description: Compiling, flashing and monitoring ADC unit test.
        command: make test_analogio_adc
        query: analogio_adc_single_board == '1:1'
        working_dir: extras/arduino-core-tests
    
    unit-test-analog-io-pwm:
      - description: Compiling, flashing and monitoring PWM unit test.
        command: make test_analogio_pwm
        query: analogio_pwm_single_board == '1:1'
        working_dir: extras/arduino-core-tests

    unit-test-pulse:
      - description: Compiling, flashing and monitoring Advanced IO Pulse unit test.
        command: make test_pulse_board1 
        query: adv_io_pulse_board1 == '1:1'
        working_dir: extras/arduino-core-tests

      - description: Compiling, flashing and monitoring Advanced IO Pulse unit test.
        command: make test_pulse_board2 
        query: adv_io_pulse_board2 == '1:1'
        working_dir: extras/arduino-core-tests

    unit-test-uart:
      - description: Compiling, flashing and monitoring UART RX unit test.
        command: make test_uart_rx 
        query: uart_multiple_boards_rx == '1:1'
        working_dir: extras/arduino-core-tests

      - description: Compiling, flashing and monitoring UART TX unit test.
        command: make test_uart_tx 
        query: uart_multiple_boards_tx == '1:1'
        working_dir: extras/arduino-core-tests

    unit-test-wifi-tcp:
      - description: Compiling, flashing and monitoring WIFI TCP server unit test.
        command: make test_wifi_server 
        query: wifi_multiple_boards_server_tcp == '1:1'
        working_dir: extras/arduino-core-tests
        options:
          RUNTIME: 150

      - description: Compiling, flashing and monitoring WIFI TCP client unit test.
        command: make test_wifi_client 
        query: wifi_multiple_boards_client_tcp == '1:1'
        working_dir: extras/arduino-core-tests
        options:
          RUNTIME: 150

    unit-test-wifi-udp:
      - description: Compiling, flashing and monitoring WIFI UDP server unit test.
        command: make test_wifi_udp_server 
        query: wifi_multiple_boards_server_udp == '1:1'
        working_dir: extras/arduino-core-tests
        options:
          RUNTIME: 150

      - description: Compiling, flashing and monitoring WIFI UDP client unit test.
        command: make test_wifi_udp_client 
        query: wifi_multiple_boards_client_udp == '1:1'
        working_dir: extras/arduino-core-tests
        options:
          RUNTIME: 150

    unit-test-wifi-sta-ap:
      - description: Compiling, flashing and monitoring WIFI Access point unit test.
        command: make test_wifi_ap 
        query: wifi_multiple_boards_ap == '1:1'
        working_dir: extras/arduino-core-tests
        options:
          RUNTIME: 150

      - description: Compiling, flashing and monitoring WIFI station unit test.
        command: make test_wifi_sta 
        query: wifi_multiple_boards_sta == '1:1'
        working_dir: extras/arduino-core-tests
        options:
          RUNTIME: 150

    unit-test-wifi-extras:
      - description: Compiling, flashing and monitoring WIFI extras test.
        command: make test_wifi_extras 
        query: wifi_single_board_extras == '1:1'
        working_dir: extras/arduino-core-tests

    unit-test-wifi-exceptions:
      - description: Compiling, flashing and monitoring WIFI exceptions test.
        command: make test_wifi_exceptions 
        query: wifi_single_board_exceptions == '1:1'
        working_dir: extras/arduino-core-tests

    unit-test-onewire-DS18x20:
      - description: Compiling, flashing and monitoring OneWire sensor DS18B20 data.
        command: make test_onewire_DS18x20 
        query: onewire_DS18x20_board == '1:1'
        working_dir: extras/arduino-core-tests
    
################### PSOC6 -063-BLE #################
    unit-test-digital-io-ble:
      - description: Compiling, flashing and monitoring digital IO unit test.
        command: make test_digitalio_single 
        query: digital_io_single_board == '2:1'
        working_dir: extras/arduino-core-tests

    unit-test-tone-ble:
      - description: Compiling, flashing and monitoring tone, no-tone unit test.
        command: make test_tone_no_tone 
        query: tone_no_tone_single_board == '2:1'
        working_dir: extras/arduino-core-tests

    unit-test-interrupts-ble:
      - description: Compiling, flashing and monitoring Interrupts unit test.
        command: make test_interrupts_single 
        query: interrupts_single_board == '2:1'
        working_dir: extras/arduino-core-tests

    unit-test-random-ble:
      - description: Compiling, flashing and monitoring random unit test.
        command: make test_random 
        query: random_single_board == '2:1'
        working_dir: extras/arduino-core-tests

    unit-test-time-ble:
      - description: Compiling, flashing and monitoring Time unit test.
        command: make test_time_single 
        query: time_single_board == '2:1'
        working_dir: extras/arduino-core-tests
  
    unit-test-iic-pingpong-ble:
      - description: Compiling, flashing and monitoring I2C pingpong slave unit test.
        command: make test_wire_connected2_slavepingpong
        query: iic_ping_pong_multiple_boards_slave == '2:1'
        working_dir: extras/arduino-core-tests

      - description: Compiling, flashing and monitoring I2C pingpong master unit test.
        command: make test_wire_connected2_masterpingpong
        query: iic_ping_pong_multiple_boards_master == '2:1'
        working_dir: extras/arduino-core-tests
          
    unit-test-spi-pingpong-ble:
      - description: Compiling, flashing and monitoring SPI pingpong slave unit test.
        command: make test_spi_connected2_slavepingpong
        query: spi_ping_pong_multiple_boards_slave == '2:1'
        working_dir: extras/arduino-core-tests

      - description: Compiling, flashing and monitoring SPI pingpong master unit test.
        command: make test_spi_connected2_masterpingpong
        query: spi_ping_pong_multiple_boards_master == '2:1'
        working_dir: extras/arduino-core-tests
          
    unit-test-spi-loopback-ble:
      - description: Compiling, flashing and monitoring SPI loopback unit test.
        command: make test_spi_connected1_loopback
        query: spi_ping_pong_single_board == '2:1'
        working_dir: extras/arduino-core-tests

    unit-test-iic-single-board-ble:
      - description: Compiling, flashing and monitoring I2C single board unit test.
        command: make test_wire_connected1_pingpong
        query: iic_ping_pong_single_board == '2:1'
        working_dir: extras/arduino-core-tests

    unit-test-analog-io-adc-ble:
      - description: Compiling, flashing and monitoring ADC unit test.
        command: make test_analogio_adc
        query: analogio_adc_single_board == '2:1'
        working_dir: extras/arduino-core-tests
    
    unit-test-analog-io-pwm-ble:
      - description: Compiling, flashing and monitoring PWM unit test.
        command: make test_analogio_pwm
        query: analogio_pwm_single_board == '2:1'
        working_dir: extras/arduino-core-tests

    unit-test-pulse-ble:
      - description: Compiling, flashing and monitoring Advanced IO Pulse unit test.
        command: make test_pulse_board1 
        query: adv_io_pulse_board1 == '2:1'
        working_dir: extras/arduino-core-tests

      - description: Compiling, flashing and monitoring Advanced IO Pulse unit test.
        command: make test_pulse_board2 
        query: adv_io_pulse_board2 == '2:1'
        working_dir: extras/arduino-core-tests

    unit-test-uart-ble:
      - description: Compiling, flashing and monitoring UART RX unit test.
        command: make test_uart_rx
        query: uart_multiple_boards_rx == '2:1'
        working_dir: extras/arduino-core-tests

      - description: Compiling, flashing and monitoring UART TX unit test.
        command: make test_uart_tx
        query: uart_multiple_boards_tx == '2:1'
        working_dir: extras/arduino-core-tests

    unit-test-onewire-DS18x20-ble:
      - description: Compiling, flashing and monitoring OneWire sensor DS18B20 data.
        command: make test_onewire_DS18x20 
        query: onewire_DS18x20_board == '2:1'
        working_dir: extras/arduino-core-tests

    unit-test-bluetooth-gatt-ble:
      - description: Compiling, flashing and monitoring Bluetooth gatt unit test.
        command: make test_bluetooth_gatt_single
        query: bluetooth_single_board == '1:1'
        working_dir: extras/arduino-core-tests

    unit-test-bluetooth-stack-ble:
      - description: Compiling, flashing and monitoring Bluetooth stack unit test.
        command: make test_bluetooth_stack_single
        query: bluetooth_single_board == '1:1'
        working_dir: extras/arduino-core-tests

    unit-test-bluetooth-connected2-ble:
      - description: Compiling, flashing and monitoring bluetooth peripheral unit test.
        command: make test_bluetooth_connected2_peripheral
        query: bluetooth_connected2_board1 == '1:1'
        working_dir: extras/arduino-core-tests

      - description: Compiling, flashing and monitoring bluetooth central unit test.
        command: make test_bluetooth_connected2_central
        query: bluetooth_connected2_board2 == '1:1'
        working_dir: extras/arduino-core-tests
    