unit-test:
    - unit-test-pulse
    - unit-test-iic-pingpong
    - unit-test-spi-pingpong
    - unit-test-digital-io
    - unit-test-time
    - unit-test-wifi-extras
    - unit-test-uart
    - unit-test-wifi-tcp
    - unit-test-interrupts
    - unit-test-tone
    - unit-test-spi-loopback
    - unit-test-wifi-exceptions
    - unit-test-analog-io-adc
    - unit-test-random
    - unit-test-analog-io-pwm
    - unit-test-iic-single-board
    - unit-test-wifi-sta-ap
    - unit-test-wifi-udp
    - unit-test-onewire-DS18x20

    ################################
    - unit-test-pulse-ble
    - unit-test-iic-pingpong-ble
    - unit-test-digital-io-ble
    - unit-test-spi-pingpong-ble
    - unit-test-time-ble
    - unit-test-interrupts-ble
    - unit-test-uart-ble
    - unit-test-tone-ble
    - unit-test-spi-loopback-ble
    - unit-test-analog-io-adc-ble
    - unit-test-random-ble
    - unit-test-analog-io-pwm-ble
    - unit-test-iic-single-board-ble
    - unit-test-onewire-DS18x20-ble
    - unit-test-bluetooth-gatt-ble
    - unit-test-bluetooth-stack-ble
    - unit-test-bluetooth-connected2-ble
